[workspace]
members = ["ask-cqrs", "ask_cqrs_macros", "example/axum_backend"]
# Only check / build main crates by default (check all with `--workspace`)
# Example has been deleted, but README.md remains
resolver = "2"
